micronaut:
  server:
    host: 0.0.0.0
    port: 8080
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - "http://localhost:3000"
            - "http://172.21.70.146:3000"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
          exposed-headers:
            - Set-Cookie
          allow-credentials: true
          max-age: 3600
  security:
    intercept-url-map:
      - pattern: "/**"
        http-method: OPTIONS
        access:
          - isAnonymous()
    enabled: true
    redirect:
      login-success: /security/success
      login-failure: /security/failure
      logout: /security/failure
    authentication: session
    basic-auth:
      enabled: false
  application:
    name: server
  cache:
    redis:
      enabled: true
  session:
    http:
      redis:
        enabled: true
        namespace: 'micronaut:session'
        write-mode: BACKGROUND
      cookie: true
      cookie-http-only: false
      cookie-path: "/"
  serde:
    serialization:
      inclusion: ALWAYS
redis:
  uri: redis://localhost:6379
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
flyway:
  datasources:
    default:
      enabled: true
      out-of-order: true
jpa:
  default:
    properties:
      hibernate:    
        hbm2ddl:
          auto: none
        order_by:
          default_null_ordering: last
